-- AlterTable
ALTER TABLE "Balance" ALTER COLUMN "balance" SET DEFAULT 0.00,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION;
